# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{excemel}
  s.version = "1.0.1"
  s.platform = %q{java}

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian Sam-Bodden"]
  s.date = %q{2011-07-20}
  s.description = %q{JRuby DSL for XML Building and Manipulation with XPath & XQuery}
  s.email = %q{bsbodden@integrallis.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "History.txt",
    "LICENSE",
    "Manifest.txt",
    "README.rdoc",
    "Rakefile",
    "lib/excemel.rb",
    "lib/excemel/excemel.rb",
    "lib/java/xom-1.2.7.jar",
    "lib/module/lang.rb",
    "lib/module/xom.rb"
  ]
  s.homepage = %q{http://github.com/bsbodden/excemel}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.1}
  s.summary = %q{JRuby DSL for XOM}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<blankslate>, ["~> 2.1.2.4"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.7"])
    else
      s.add_dependency(%q<blankslate>, ["~> 2.1.2.4"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 3.7"])
    end
  else
    s.add_dependency(%q<blankslate>, ["~> 2.1.2.4"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 3.7"])
  end
end

